export {
  globals,
  comment,
  use,
  import,
  declare,
  export,
  const,
  let,
  if,
  do,
  void,
  func,
  class,
  throw,
  new,
  typeof,
  oftype,
  await,
  instof,
  in,
  is,
  isNil,
  isSome,
  list,                  list                  as ':',
  dict,                  dict                  as '::',
  get,                   get                   as '<-',
  set,                   set                   as '->',
  assign,                assign                as '=',
  and,                   and                   as '&&',
  or,                    or                    as '||',
  coalesce,              coalesce              as '??',
  not,                   not                   as '!',
  yes,                   yes                   as '!!',
  eq,                    eq                    as '===',
  neq,                   neq                   as '!==',
  gt,                    gt                    as '>',
  lt,                    lt                    as '<',
  gte,                   gte                   as '>=',
  lte,                   lte                   as '<=',
  add,                   add                   as '+',
  subtract,              subtract              as '-',
  divide,                divide                as '/',
  multiply,              multiply              as '*',
  exponentiate,          exponentiate          as '**',
  remainder,             remainder             as '%',
  bitNot,                bitNot                as '~',
  bitAnd,                bitAnd                as '&',
  bitOr,                 bitOr                 as '|',
  bitXor,                bitXor                as '^',
  bitShiftLeft,          bitShiftLeft          as '<<',
  bitShiftRight,         bitShiftRight         as '>>',
  bitShiftRightUnsigned, bitShiftRightUnsigned as '>>>',
  assignIncrement,       assignIncrement       as '++',
  assignDecrement,       assignDecrement       as '--',
  regexp,
} from './mac.mjs'
